exclude: (^asv_bench|setup.py|requirements-dev.txt)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
        description: Simply check whether files parse as valid python
      - id: check-case-conflict
        description: Check for files that would conflict in case-insensitive filesystems
      - id: check-docstring-first
        description: Checks for a common error of placing code before the docstring.
      - id: check-merge-conflict
        description: Check for files that contain merge conflict strings
      - id: check-yaml
        description: Attempts to load all yaml files to verify syntax
      - id: debug-statements
        description: Check for debugger imports and py37+ breakpoint() calls in python source
      - id: end-of-file-fixer
        description: Makes sure files end in a newline and only a newline
      - id: trailing-whitespace
        description: Trims trailing whitespace
      - id: mixed-line-ending
        description: Replaces or checks mixed line ending

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--line-length=79", "--skip=docs/source/conf.py", "--diff"]

  - repo: https://github.com/ikamensh/flynt
    rev: '0.76'
    hooks:
        - id: flynt

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length=79"]

  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        args: ["--disable=import-error"]
        exclude: (^docs/|^scripts)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        files: (^pandera/|^tests|^scripts)
        exclude: (^docs/|^tests/mypy/modules/)
        additional_dependencies:
        - types-click
        - types-pyyaml
        - types-pkg_resources
        - types-requests
        - types-pytz
